name: Novius CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint-php:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Lint PHP code via Laravel Pint
        run: composer run-script lint

  phpstan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3', '8.4']
        laravel: [ 11.*, 12.* ]
        filament: [ 4.*, 5.* ]
        include:
          - laravel: 12.*
            carbon: 3.*
            testbench: 10.*
          - laravel: 11.*
            carbon: 2.*
            testbench: 9.*
          - php-versions: '8.2'
            pest: '^3.0'
          - php-versions: '8.3'
            pest: '^4.0'
          - php-versions: '8.4'
            pest: '^4.0'
        exclude:
          - php-versions: '8.2'
            filament: 5.*

    name: phpstan - P${{ matrix.php-versions }} - L${{ matrix.laravel }} - F${{ matrix.filament }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "filament/filament:${{ matrix.filament }}" "nesbot/carbon:${{ matrix.carbon }}" "orchestra/testbench:${{ matrix.testbench }}" "pestphp/pest:${{ matrix.pest }}" "pestphp/pest-plugin-laravel:${{ matrix.pest }}" --no-interaction --no-update
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: PhPStan
        run: composer run-script phpstan

  phpunit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3', '8.4']
        laravel: [ 11.*, 12.* ]
        filament: [ 4.*, 5.* ]
        include:
          - laravel: 12.*
            carbon: 3.*
            testbench: 10.*
          - laravel: 11.*
            carbon: 2.*
            testbench: 9.*
          - php-versions: '8.2'
            pest: '^3.0'
          - php-versions: '8.3'
            pest: '^4.0'
          - php-versions: '8.4'
            pest: '^4.0'
        exclude:
          - php-versions: '8.2'
            filament: 5.*

    name: phpunit - P${{ matrix.php-versions }} - L${{ matrix.laravel }} - F${{ matrix.filament }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "filament/filament:${{ matrix.filament }}" "nesbot/carbon:${{ matrix.carbon }}" "orchestra/testbench:${{ matrix.testbench }}" "pestphp/pest:${{ matrix.pest }}" "pestphp/pest-plugin-laravel:${{ matrix.pest }}" --no-interaction --no-update
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Pest
        run: vendor/bin/pest
